#!/usr/bin/env bash
# send a file to server
if [ -z "$3" ];then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ -z "$4" ]; then
  scp -B "$1" "$3"@"$2":
else
  scp -B -i "$4" "$1" "$3"@"$2":
fi
