#!/usr/bin/env bash
# install and configure nginx
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
hos=$(hostname | cut -d '@' -f2)
echo "server {
     listen 80 default_server;
     listen [::]:80 default_server;
     root /var/www/html;
     add_header X-Served-By ${hos};
     index index.nginx-debian.html;
     location /redirect_me {
         return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
     }
     error_page 404 /404.html;
     location = /404.html {
         root /var/www/html;
         internal;
     }
}" > /etc/nginx/sites-available/default

service nginx restart
