#!/usr/bin/env bash
#  displays the PID, along with the process name, of
# processes whose name contain the word bash
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)
if [-n "$id" ]
then
	kill -15 "$id"
fi
